version: "3.8"

services:
  mongo1:
    container_name: mongo1
    image: mongo:6.0.11
    hostname: mongo1
    command: ["mongod", "--replSet", "rs0"]
    restart: "always"
    ports:
      - 1972:27017
    networks:
      - mongo-network
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
  mongosetup:
    container_name: mongosetup
    image: mongo:6.0.11
    restart: "no"
    networks:
      - mongo-network
    depends_on:
      - mongo1
    command: ["bash", "-c", "sleep 3 && mongosh --host mongo1:27017 --eval \"rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongo1:27017'}]})\""]
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
  # ovs-discord-bot:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: ovs-discord-bot
  #   restart: "always"
  #   environment:
  #     - .env
  #   volumes:
  #     - ./:/usr/src/app

volumes:
  mongo1_data:
  mongo1_config:

networks:
  mongo-network:


